import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export const availableLanguages = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'am', name: 'አማርኛ', flag: '🇪🇹' },
  { code: 'ti', name: 'ትግርኛ', flag: '🇪🇷' },
  { code: 'om', name: 'Oromoo', flag: '🇪🇹' },
  { code: 'so', name: 'Soomaali', flag: '🇸🇴' },
]

const translations = {
  en: {
    tagline: 'Learn Ethiopian Languages',
    subtitle: 'Master Amharic, Tigrinya, Afaan Oromo, Somali, and English through fun, bite-sized lessons.',
    getStarted: 'Get Started',
    haveAccount: 'I Already Have an Account',
    freeForever: 'Free forever • No credit card needed',
    login: 'Log In',
    welcomeBack: 'Welcome back!',
    loginToContinue: 'Log in to continue learning',
    createProfile: 'Create your profile',
    startJourney: 'Start your language learning journey',
    email: 'Email',
    password: 'Password',
    username: 'Username',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    chooseUsername: 'Choose a username',
    createPassword: 'Create a password',
    createAccount: 'Create Account',
    noAccount: "Don't have an account?",
    signUp: 'Sign up',
    alreadyHaveAccount: 'Already have an account?',
    checkEmail: 'Check your email!',
    confirmationSent: "We've sent a confirmation link to",
    goToLogin: 'Go to Login',
    or: 'OR',
    atLeast6Chars: 'At least 6 characters',
    terms: 'By signing up, you agree to our Terms of Service and Privacy Policy',
    phone: 'Phone Number',
    enterPhone: 'Enter your phone number',
    heroTitle: 'The free, fun, and effective way to learn a language!',
    heroFeature1: 'Bite-sized lessons',
    heroFeature2: 'Track your progress',
    heroFeature3: 'Learn at your pace',
    aboutTitle: 'Discover Ethiopia\'s Rich Linguistic Heritage',
    aboutText: 'Ethiopia is home to over 80 languages, making it one of the most linguistically diverse countries in Africa. From Amharic, the official language with its unique Ge\'ez script, to Tigrinya, Afaan Oromo, and Somali  each language carries centuries of culture, poetry, and tradition.',
    missionTitle: 'Our Mission',
    missionText: 'We\'re bringing these beautiful languages to the world through modern, interactive learning. Whether you\'re connecting with heritage, preparing for travel, or simply curious  start your journey today.',
  },
  am: {
    tagline: 'የኢትዮጵያ ቋንቋዎችን ይማሩ',
    subtitle: 'አማርኛ፣ ትግርኛ፣ አፋን ኦሮሞ፣ ሶማሊኛ እና እንግሊዝኛን በአስደሳች ትምህርቶች ይማሩ።',
    getStarted: 'ጀምር',
    haveAccount: 'አካውንት አለኝ',
    freeForever: 'ለዘላለም ነፃ • ክሬዲት ካርድ አያስፈልግም',
    login: 'ግባ',
    welcomeBack: 'እንኳን ደህና መጡ!',
    loginToContinue: 'መማርዎን ለመቀጠል ይግቡ',
    createProfile: 'መገለጫዎን ይፍጠሩ',
    startJourney: 'የቋንቋ ትምህርት ጉዞዎን ይጀምሩ',
    email: 'ኢሜይል',
    password: 'የይለፍ ቃል',
    username: 'የተጠቃሚ ስም',
    enterEmail: 'ኢሜይልዎን ያስገቡ',
    enterPassword: 'የይለፍ ቃልዎን ያስገቡ',
    chooseUsername: 'የተጠቃሚ ስም ይምረጡ',
    createPassword: 'የይለፍ ቃል ይፍጠሩ',
    createAccount: 'አካውንት ፍጠር',
    noAccount: 'አካውንት የለዎትም?',
    signUp: 'ይመዝገቡ',
    alreadyHaveAccount: 'አካውንት አለዎት?',
    checkEmail: 'ኢሜይልዎን ይፈትሹ!',
    confirmationSent: 'የማረጋገጫ ሊንክ ልከናል ወደ',
    goToLogin: 'ወደ መግቢያ ሂድ',
    or: 'ወይም',
    atLeast6Chars: 'ቢያንስ 6 ቁምፊዎች',
    terms: 'በመመዝገብ የአገልግሎት ውሎቻችንን እና የግላዊነት ፖሊሲን ይቀበላሉ',
    phone: 'ስልክ ቁጥር',
    enterPhone: 'ስልክ ቁጥርዎን ያስገቡ',
    heroTitle: 'ቋንቋ ለመማር ነፃ፣ አስደሳች እና ውጤታማ መንገድ!',
    heroFeature1: 'አጫጭር ትምህርቶች',
    heroFeature2: 'እድገትዎን ይከታተሉ',
    heroFeature3: 'በራስዎ ፍጥነት ይማሩ',
    aboutTitle: 'የኢትዮጵያን ሀብታም የቋንቋ ቅርስ ያግኙ',
    aboutText: 'ኢትዮጵያ ከ80 በላይ ቋንቋዎች መኖሪያ ናት፣ ይህም በአፍሪካ ውስጥ በቋንቋ ልዩነት ከሚታወቁ አገሮች አንዷ ያደርጋታል። ከአማርኛ፣ ከትግርኛ፣ ከአፋን ኦሮሞ እስከ ሶማሊኛ  እያንዳንዱ ቋንቋ የዘመናት ባህል፣ ግጥም እና ወግ ይዟል።',
    missionTitle: 'ተልዕኮአችን',
    missionText: 'እነዚህን ቆንጆ ቋንቋዎች በዘመናዊ እና በይነተገናኝ ትምህርት ወደ ዓለም እናመጣለን። ከቅርስዎ ጋር ለመገናኘት፣ ለጉዞ ለመዘጋጀት ወይም በቀላሉ ለማወቅ  ዛሬ ጉዞዎን ይጀምሩ።',
  },
  ti: {
    tagline: 'ናይ ኢትዮጵያ ቋንቋታት ተማሃሩ',
    subtitle: 'ኣማርኛ፣ ትግርኛ፣ ኦሮምኛ፣ ሶማልኛን እንግሊዝኛን ብዘሐጎሱ ትምህርትታት ተማሃሩ።',
    getStarted: 'ጀምር',
    haveAccount: 'ኣካውንት ኣለኒ',
    freeForever: 'ንዘለኣለም ነጻ',
    login: 'እቶ',
    welcomeBack: 'እንኳዕ ደሓን መጻእኩም!',
    loginToContinue: 'ምምሃር ንምቕጻል እቶ',
    createProfile: 'መግለጺኻ ፍጠር',
    startJourney: 'ናይ ቋንቋ ትምህርቲ ጉዕዞኻ ጀምር',
    email: 'ኢመይል',
    password: 'ምስጢር ቃል',
    username: 'ስም ተጠቃሚ',
    enterEmail: 'ኢመይልካ ኣእቱ',
    enterPassword: 'ምስጢር ቃልካ ኣእቱ',
    chooseUsername: 'ስም ተጠቃሚ ምረጽ',
    createPassword: 'ምስጢር ቃል ፍጠር',
    createAccount: 'ኣካውንት ፍጠር',
    noAccount: 'ኣካውንት የብልካን?',
    signUp: 'ተመዝገብ',
    alreadyHaveAccount: 'ኣካውንት ኣለካ?',
    checkEmail: 'ኢመይልካ ርአ!',
    confirmationSent: 'ናይ መረጋገጺ ሊንክ ሰዲድናልካ',
    goToLogin: 'ናብ መእተዊ ኪድ',
    or: 'ወይ',
    atLeast6Chars: 'እንተወሓደ 6 ፊደላት',
    terms: 'ብምምዝጋብ ናይ ኣገልግሎት ውዕልን ናይ ብሕትውና ፖሊሲን ትቕበል',
    heroTitle: 'ቋንቋ ንምምሃር ነጻ፣ ዘሐጉስን ውጽኢታውን መንገዲ!',
    heroFeature1: 'ሓጸርቲ ትምህርትታት',
    heroFeature2: 'ምዕባለኻ ተኸታተል',
    heroFeature3: 'ብናትካ ፍጥነት ተማሃር',
  },
  om: {
    tagline: 'Afaanota Itoophiyaa Baradhu',
    subtitle: 'Afaan Amaaraa, Tigirinyaa, Oromoo, Somaalee fi Inglizii barnoota gabaabaadhaan baradhu.',
    getStarted: 'Jalqabi',
    haveAccount: 'Herrega qaba',
    freeForever: 'Yeroo hundaaf bilisaa',
    login: 'Seeni',
    welcomeBack: 'Baga nagaan dhufte!',
    loginToContinue: 'Barachuu itti fufuuf seeni',
    createProfile: 'Profaayilii kee uumi',
    startJourney: 'Imala barumsaa afaanii kee jalqabi',
    email: 'Imeelii',
    password: 'Jecha darbii',
    username: 'Maqaa fayyadamaa',
    enterEmail: 'Imeelii kee galchi',
    enterPassword: 'Jecha darbii kee galchi',
    chooseUsername: 'Maqaa fayyadamaa filadhu',
    createPassword: 'Jecha darbii uumi',
    createAccount: 'Herrega Uumi',
    noAccount: 'Herrega hin qabduu?',
    signUp: 'Galmaa\'i',
    alreadyHaveAccount: 'Herrega qabdaa?',
    checkEmail: 'Imeelii kee ilaali!',
    confirmationSent: 'Liinkii mirkaneessaa ergineerra',
    goToLogin: 'Gara Seensaatti deemi',
    or: 'YKN',
    atLeast6Chars: 'Yoo xiqqaate qubee 6',
    terms: 'Galmaa\'uudhaan Haala Tajaajilaa fi Imaammata Dhuunfaa fudhatta',
    heroTitle: 'Afaan barachuuf karaa bilisaa, gammachiisaa fi bu\'a qabeessa!',
    heroFeature1: 'Barnoota gabaabaa',
    heroFeature2: 'Guddina kee hordofi',
    heroFeature3: 'Saffisa keetiin baradhu',
  },
  so: {
    tagline: 'Baro Luuqadaha Itoobiya',
    subtitle: 'Ku baro Amxaariga, Tigrinya, Oromiffa, Soomaaliga iyo Ingiriisiga casharro kooban oo xiiso leh.',
    getStarted: 'Bilow',
    haveAccount: 'Koonto ayaan haystaa',
    freeForever: 'Bilaash weligeed',
    login: 'Soo gal',
    welcomeBack: 'Ku soo dhawoow!',
    loginToContinue: 'Soo gal si aad u sii wado barashada',
    createProfile: 'Samee profile-kaaga',
    startJourney: 'Bilow safarkaaga barashada luuqadda',
    email: 'Iimaylka',
    password: 'Furaha sirta',
    username: 'Magaca isticmaalaha',
    enterEmail: 'Geli iimaylkaaga',
    enterPassword: 'Geli furaha sirta',
    chooseUsername: 'Dooro magac isticmaale',
    createPassword: 'Samee furaha sirta',
    createAccount: 'Samee Koonto',
    noAccount: 'Koonto ma haysatid?',
    signUp: 'Is diiwaan geli',
    alreadyHaveAccount: 'Koonto ma haysataa?',
    checkEmail: 'Hubi iimaylkaaga!',
    confirmationSent: 'Waxaan kuu dirnay link xaqiijin',
    goToLogin: 'Aad Gelitaanka',
    or: 'AMA',
    atLeast6Chars: 'Ugu yaraan 6 xaraf',
    terms: 'Markaad is diiwaan geliso, waxaad aqbashaa Shuruudaha Adeegga iyo Siyaasadda Asturnaanta',
    heroTitle: 'Habka bilaashka ah, xiisaha leh, ee wax ku oolka ah ee luuqad lagu barto!',
    heroFeature1: 'Cashar kooban',
    heroFeature2: 'Raac horumaarkaaga',
    heroFeature3: 'Ku baro xawligaaga',
  },
}

const useLanguageStore = create(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (language) => set({ language }),
      t: (key) => {
        const { language } = get()
        return translations[language]?.[key] || translations.en[key] || key
      },
    }),
    {
      name: 'adewe-language',
    }
  )
)

export default useLanguageStore
